on: push
jobs:
  gcc-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: johelegp/gcc-snapshot@v1
      - uses: actions/checkout@v2
      - uses: johelegp/modern-cmake-buildsystem@v1 # This action.
        with:
          generate-options: "--preset=test"
